export const thumbnailOptions = [
  {
    id: 'change',
    href: '/film',
    title: 'Change',
    category: 'Short Film — 2026',
    image: '/images/change-hero.jpg',
  },
  {
    id: 'etwscope',
    href: '/#research',
    title: 'EtwScope',
    category: 'Security Research — STCMF',
    image: '/images/thumb-etwscope.jpg',
  },
  {
    id: 'kynettic',
    href: '#works-kynettic',
    title: 'Kynettic',
    category: 'Security Research',
    image: '/images/kynettic-logo.png',
  },
  {
    id: 'phlexit',
    href: '#works-phlexit',
    title: 'Phlexit',
    category: 'Backend Engineer',
    image: '/images/thumb-phlexit.jpg',
  },
  {
    id: 'nema',
    href: '#works-nema',
    title: 'NEMA',
    category: 'Security Operations — Nigeria',
    image: '/images/thumb-nema.jpg',
  },
  {
    id: 'ide',
    href: '#works-ide',
    title: 'IDE',
    category: 'Fullstack Engineer',
    image: '/images/thumb-ide.jpg',
  },
  {
    id: '234coins',
    href: '#works-234coins',
    title: '234coins.net',
    category: 'Cloud — Freelance',
    image: '/images/thumb-234coins.jpg',
  },
  {
    id: 'gigafro',
    href: '#works-gigafro',
    title: 'GigAfro',
    category: 'Startup Marketplace',
    image: '/images/thumb-gigafro.jpg',
  },
  {
    id: 'htb',
    href: '#works-htb',
    title: 'HackTheBox',
    category: 'CPTS — Certified',
    image: '/images/thumb-htb.jpg',
  },
  {
    id: 'hackathon',
    href: '#works-hackathon',
    title: 'Hackathons',
    category: 'Gemini · Opik Comet',
    image: '/images/thumb-hackathon.jpg',
  },
  {
    id: 'codesandbox',
    href: 'https://github.com/codesandbox/codesandbox-client/security/advisories/GHSA-5jw5-g7mr-h26r',
    title: 'CodeSandbox',
    category: 'CVE / Disclosure',
    image: '/images/thumb-csb.jpg',
  },
  {
    id: 'talks',
    href: '#talks',
    title: 'Talks',
    category: 'Presentations',
    image: '/images/thumb-talks.jpg',
  },
];
