export const thumbnailOptions = [
  {
    id: 'change',
    href: '/film',
    title: 'Change',
    category: 'Short Film — 2026',
    image: '/images/change-hero.jpg',
  },
  {
    id: 'etwscope',
    href: '/about#research',
    title: 'EtwScope',
    category: 'Security Research — STCMF',
    image: '/images/thumb-etwscope.jpg',
  },
  {
    id: 'kynettic',
    href: '/about#works-kynettic',
    title: 'Kynettic',
    category: 'Security Research',
    image: '/images/kynettic-logo.png',
  },
  {
    id: 'phlexit',
    href: '/about#works-phlexit',
    title: 'Phlexit',
    category: 'Backend Engineer',
    image: '/images/thumb-phlexit.jpg',
  },
  {
    id: 'nema',
    href: '/about#works-nema',
    title: 'NEMA',
    category: 'Security Operations — Nigeria',
    image: '/images/thumb-nema.jpg',
  },
  {
    id: 'ide',
    href: '/about#works-ide',
    title: 'Stonerockers / IDE',
    category: 'Fullstack Engineer',
    image: '/images/thumb-ide.jpg',
  },
  {
    id: '234coins',
    href: '/about#works-234coins',
    title: '234coins.net',
    category: 'Cloud — Freelance (Upwork)',
    image: '/images/thumb-upwork.jpg',
  },
  {
    id: 'gigafro',
    href: '/about#works-gigafro',
    title: 'StreetVibez',
    category: 'Startup Marketplace (GigAfro)',
    image: '/images/thumb-gigafro.jpg',
  },
  {
    id: 'htb',
    href: '/about#works-htb',
    title: 'HackTheBox',
    category: 'CPTS — Certified',
    image: '/images/thumb-htb.jpg',
  },
  {
    id: 'hackathon',
    href: '/about#works-hackathon',
    title: 'Hackathons',
    category: 'Gemini · Opik Comet',
    image: '/images/thumb-hackathon.jpg',
  },
  {
    id: 'codesandbox',
    href: 'https://codesandbox.io/',
    title: 'CodeSandbox',
    category: 'CVE / Disclosure',
    image: '/images/thumb-csb.jpg',
  },
  {
    id: 'talks',
    href: '/about#talks',
    title: 'Talks',
    category: 'Presentations',
    image: '/images/thumb-talks.jpg',
  },
];
