export const experience = [
  {
    slug: 'kynettic',
    tag: 'Security Engineer',
    title: 'Kynettic',
    role: 'Lead Security Engineer (Contract)',
    dates: 'July 2026 – Present',
    image: '/images/kynettic-logo.png',
    bullets: [
      'Web, API and mobile security assessments across authentication, authorization, session management, business logic and injection.',
      'Protocol-layer and application security in DeFi systems: swap-logic integrity, access control and transaction validation.',
      'Structured reports with severity ratings, reproduction steps and prioritized remediation.',
    ],
  },
  {
    slug: 'nema',
    tag: 'Security Operations',
    title: 'NEMA-HQ',
    role: 'Security Operations Specialist (Internship)',
    dates: 'June 2025 – January 2026',
    href: 'https://nema.gov.ng/about-nema/',
    image: '/images/thumb-nema.jpg',
    bullets: [
      'Live government SOC security event monitoring, SIEM alert triage and incident response.',
      'Active Directory and endpoint hardening on HP ProLiant with MikroTik, Cisco and EDR.',
      'Vulnerability assessment of network assets incl. Huawei NetEngine CX600; supported GIS data-relay and Mission Control.',
    ],
  },
  {
    slug: 'atl',
    tag: 'Technical Security Writer',
    title: 'ATL Labs (PinkDraconian)',
    role: 'Technical Security Writer',
    dates: 'June 14 – July 29, 2025',
    image: '/images/thumb-atl.jpg',
    bullets: [
      'Developed RBAC security courseware on access-control architecture, policy design and enforcement.',
      'Research and technical writing on identity management and security governance for practitioners.',
    ],
  },
  {
    slug: 'phlexit',
    tag: 'Backend Developer',
    title: 'Phlex IT Events',
    role: 'Staff Backend Developer',
    dates: 'April 2024 – July 2025',
    href: 'https://www.myphlexit.com/',
    image: '/images/thumb-phlexit.jpg',
    bullets: [
      'REST APIs with NestJS and PostgreSQL for auth, OTP verification, session management and ticketing at scale.',
      'Server-side pagination and caching across 50,000+ attendee records; MongoDB ORM and CI/CD.',
    ],
  },
  {
    slug: 'ide',
    tag: 'Web & System Architect',
    title: 'IDE Nigeria',
    role: 'Sr. Website Developer & System Architect (Contract)',
    dates: 'January 2021 – January 2026',
    href: 'https://stonerockers.com/',
    image: '/images/thumb-ide.jpg',
    bullets: [
      'Multi-company operations platform (Simdozi, Marblefoods, Stonerockers, Aoahomes, BigHomes) with Node.js, Laravel, Three.js, C# and Azure.',
      'Mobile-first responsive UI with Tailwind CSS (+57% engagement); resolved IAM misconfigurations and cloud deployment issues.',
    ],
  },
  {
    slug: '234coins',
    tag: 'Cloud — Freelance (Upwork)',
    title: '234coins.net',
    role: 'AWS Cloud Engineer',
    dates: 'December 2023',
    href: 'https://www.upwork.com/',
    image: '/images/thumb-upwork.jpg',
    bullets: [
      'Optimized AWS IAM service roles, reducing deployment errors by 50% on the Unity runtime engine.',
      'Diagnosed cloud CORS misconfigurations and reliability issues.',
      'Real-time Redis monitoring for token loading and device activity.',
    ],
  },
  {
    slug: 'gigafro',
    tag: 'Startup Marketplace',
    title: 'GigAfro / StreetVibez',
    role: 'Security Engineer — Freelance Marketplace',
    dates: 'January 2026',
    href: 'https://streetvibex.com/',
    image: '/images/thumb-gigafro.jpg',
    bullets: [
      'Built and launched a production marketplace connecting freelancers to gigs with real-time geolocation and ranking.',
      'Designed a dispatch system across Android, iOS and web clients in a live production environment.',
    ],
  },
];

export const disclosures = [
  {
    vendor: 'Google Chrome',
    title: 'Polyglot ZIP executed as HTML (stored XSS via MIME discard)',
    status: 'Triaged',
    year: '2026',
    link: 'https://issues.chromium.org/issues/509555616',
  },
  {
    vendor: 'Elastic',
    title: 'APM Server API key cache bypasses secret validation + DoS',
    status: 'Triaged',
    year: '2026',
    link: 'https://hackerone.com/reports/3715105',
  },
  {
    vendor: 'Elastic',
    title: 'Arbitrary file write via intake-receiver path traversal',
    status: 'Triaged',
    year: '2026',
    link: 'https://hackerone.com/reports/3711987',
  },
  {
    vendor: 'X / xAI',
    title: 'Messaging restriction bypass via post-sharing (Community Notes)',
    status: 'Triaged · Open',
    year: '2026',
    link: 'https://hackerone.com/reports/3954160',
  },
  {
    vendor: 'Rockstar Games',
    title: 'Reflected XSS on VPN getconfig.esp (CVE-2025-0133)',
    status: 'Triaged',
    year: '2025',
    link: 'https://hackerone.com/reports/3277292',
  },
  {
    vendor: 'Figma',
    title: 'IDOR on chapter membership (deleted / deactivated chapters)',
    status: 'Triaged',
    year: '2025',
    link: 'https://hackerone.com/reports/3339899',
  },
  {
    vendor: 'Syfe',
    title: 'Web Cache Deception via semicolon delimiter (api.syfe.com)',
    status: 'Triaged',
    year: '2026',
    link: 'https://hackerone.com/reports/3530679',
  },
  {
    vendor: 'CodeSandbox',
    title: 'High-severity GraphQL VM allocation bypass (GHSA-5jw5-g7mr-h26r)',
    status: 'Credited',
    year: '2024',
    link: 'https://github.com/codesandbox/codesandbox-client/security/advisories/GHSA-5jw5-g7mr-h26r',
  },
];

export const ctfs = [
  { title: 'HackTheBox — CPTS Certified', meta: 'Active Directory, pentesting, vuln assessment · Feb 2024', href: 'https://profile.hackthebox.com/profile/01a03172-185e-72bf-b83a-4197965a8404' },
  { title: 'TryHackMe', meta: 'CTF / hands-on security labs', href: 'https://tryhackme.com/p/populistpreventi' },
  { title: 'CyberSafe HQ — HackTheBox 1st Place', meta: 'Competition winner · 2023' },
  { title: 'Gemini Hackathon — LiDAR Spatial Assistant', meta: 'Special Recognition · Feb 2026', href: 'https://gemini3.devpost.com/' },
  { title: 'Opik Comet — AI Budgeting Agent', meta: 'Runner-Up · Jan 2026' },
  { title: 'NCAIR Hackathon — Dementia Chatbot', meta: 'Winner · $1,000 grant · Sep 2025' },
  { title: 'CTFtime — team 303681', meta: 'Competitive CTF team', href: 'https://ctftime.org/team/303681' },
  {
    title: 'Gray Swan Arena',
    meta: 'LLM red teaming — prompt injection, jailbreaks and agent safety',
    href: 'https://app.grayswan.ai/profile',
    details: [
      'Global Rank #924 · 220 points · 12 unique breaks',
      '1,226 submissions in the last year',
      'IPI Lucky Break — #103 of 485 · 11 breaks',
      'Indirect Prompt Injection Aug 2026 — #133 of 807 · 24 breaks',
      'Indirect Prompt Injection Jul 2026 — #201 of 473 · 1 break',
    ],
  },
  {
    title: 'Judgement Day — AI Red Team Arena',
    meta: 'AIM Intelligence × Korea AISI · global AI safety competition (Apr–May 2026)',
    href: 'https://app.grayswan.ai/profile',
    details: [
      'Global Rank #59 · 149.00 points · 399 approved submissions',
      '27 breaches · 7% breach rate',
      'Epidemiological Surveillance — 35 pts · 5/23',
      'Emergency Triage — 33 pts · 7/93',
      'Industrial Robot — 25 pts · 6/57',
      'Deepfake Detection — 16 pts · 3/34',
      'Cybersecurity SOC — 14 pts · 2/45',
      'Dam Flood Control — 12 pts · 2/25',
      'Sports Integrity — 9 pts · 1/62',
      'Aircraft Predictive Maintenance — 5 pts · 1/60',
    ],
  },
];

export const talks = [
  {
    title: 'Threat detection approaches for iOS application architecture',
    meta: 'FUT Minna — CyberNexus Starter · 2026',
    detail: 'Malware analysis, reverse engineering and antimalware techniques.',
  },
  {
    title: 'Wireless phishing attacks & awareness (Airgeddon)',
    meta: 'NACSS Cybersecurity Awareness Month, Al-Amin Secondary School · 2023',
    detail: 'Practical wireless phishing demonstration and awareness session.',
  },
];

export const projects = [
  { title: 'GigAfro / StreetVibez', meta: 'Live freelance marketplace · Flutter, Swift, React, GraphQL · Jan 2026', href: 'https://streetvibex.com/', done: true },
  { title: 'Conversational AI for Dementia Care', meta: 'NCAIR · emotion-aware dialogue · $1k grant · 2025', done: true },
  { title: 'LiDAR Spatial Assistant for Blind Users', meta: 'Gemini Hackathon · ARKit, YOLOv9, ARCore · 2026', done: true },
  { title: 'AI Budgeting Agent', meta: 'Opik Comet Runner-Up · MCP stack · 2026', done: true },
  { title: 'Azure Stack USSD', meta: 'Scalable USSD on Azure Stack Hub + Africa’s Talking · 2023', done: true },
  { title: 'Video Storybook', meta: 'AI storyboarding: MiDaS, TensorFlow, ControlNet', done: true },
  { title: 'Soccer Behavioural Analysis (SBA)', meta: 'Mobile analysis app for player mood & performance', done: true },
  { title: 'Circles (snapBLE)', meta: 'P2P low-bitrate Bluetooth video calling protocol', done: true },
  { title: 'React-OauthRouter', meta: 'OAuth for react-router (Facebook, Google, GitHub, LinkedIn, Twitter)', done: true, href: 'https://github.com/d3vobed' },
  { title: 'AFTNStreamDecoder', meta: 'Decoder for ATS emergency-signal messages, ML-assisted', done: true },
  { title: 'Chameleon', meta: 'Volumetric facial scanner for facial replacement in film', done: false },
  { title: 'Autobot OS', meta: 'Python & C++ OS for file management, retrieval and admin tasks', done: false },
];